name: Pages Publish
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: rss-data-updated
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yqq git build-essential

    - name: Setup ruby
      run: |
        gem install bundler -v 2.5.6
        bundle install --jobs 4 --retry 3

    - name: Generate site
      run: |
        bundle exec jekyll build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

    - name: Setup SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.DEPLOY_KNOWN_HOSTS }}

    - name: Update Deployment
      run: |
        ssh deploy@site.smartlogic.io \
          -o IdentitiesOnly=yes \
          -C "cd sites/smartlogic.io && git pull origin gh-pages"
